package org.intermine.bio.web.displayer;

import java.util.ArrayList;
import java.util.Set;

import javax.servlet.http.HttpServletRequest;

import org.apache.log4j.Logger;
import org.intermine.api.InterMineAPI;
import org.intermine.model.InterMineObject;
import org.intermine.model.bio.Pathway;

import org.intermine.web.displayer.ReportDisplayer;
import org.intermine.web.logic.config.ReportDisplayerConfig;
import org.intermine.web.logic.results.ReportObject;

/**
 * Class used for retrieval and handling of information used in the display
 * of a Pathways (and maybe their intersections) in Targetmine
 *
 * @author Rodolfo Allendes
 * @version 0.1
 */
public class PathwayGraphDisplayer extends ReportDisplayer{
  /* define a LOG to post messages to */
  protected static final Logger logger = Logger.getLogger(PathwayGraphDisplayer.class);

  /**
   * Constructor
   * Use super class to initialize required components
   */
  public PathwayGraphDisplayer(ReportDisplayerConfig config, InterMineAPI im){
    super(config,im);
  }

  /**
   *
   * @param request
   * @param reportObject
   */
  @SuppressWarnings("unchecked")
  @Override
  public void display(HttpServletRequest request, ReportObject reportObject){

    // A list of data elements that we will forward to Javascript for the
    // definition of the graph - for now its hard-coded, but should be loaded
    // from the XML used by KEGG together with the information generated by
    // Chikamori-san
    ArrayList<String> data = new ArrayList<String>();
    String header = "shape\t"+
      "text\t"+
      "x\t"+
      "y\t"+
      "width\t"+
      "height\t"+
      "fill";
    String row; // we will use this to add elements to the data array
    data.add(header);

    // hard coded in the meantime
    //Pathway pathway = (Pathway)reportObject.getObject();

  // <pathway name="path:hsa05010" org="hsa" number="05010"
  //          title="Alzheimer disease"
  //          image="https://www.kegg.jp/kegg/pathway/hsa/hsa05010.png"
    //          link="https://www.kegg.jp/kegg-bin/show_pathway?hsa05010">
    // <entry id="70" name="hsa:1020" type="gene"
    //     link="https://www.kegg.jp/dbget-bin/www_bget?hsa:1020">
    //     <graphics name="CDK5, LIS7, PSSALRE" fgcolor="#000000" bgcolor="#BFFFBF"
    //          type="rectangle" x="498" y="792" width="46" height="17"/>
    // </entry>

    String shape = "rectangle";
    String text = "CDK5";
    String x = "498";
    String y = "792";
    String width = "46";
    String height = "17";
    String fill = "#BFFFBF";

    row = shape+"\t";
    row += (text+"\t");
    row += (x+"\t");
    row += (y+"\t");
    row += (width+"\t");
    row += (height+"\t");
    row += fill;
    data.add(row);

    text = "PSENEN";//, ACNINV2, MDS033, MSTP064, PEN-2, PEN2";
    x = "379"; y = "280";
    row = shape+"\t";
    row += (text+"\t");
    row += (x+"\t");
    row += (y+"\t");
    row += (width+"\t");
    row += (height+"\t");
    row += fill;
    data.add(row);

    text="PSEN1";//, ACNINV3, AD3, FAD, PS-1, PS1, S182...";
    x="425"; y="280";
    row = shape+"\t";
    row += (text+"\t");
    row += (x+"\t");
    row += (y+"\t");
    row += (width+"\t");
    row += (height+"\t");
    row += fill;
    data.add(row);

    text="NCSTN";//, ATAG1874";
    x="379"; y="297";
    row = shape+"\t";
    row += (text+"\t");
    row += (x+"\t");
    row += (y+"\t");
    row += (width+"\t");
    row += (height+"\t");
    row += fill;
    data.add(row);

    text="APH1A";//, 6530402N02Rik, APH-1, APH-1A, CGI-78...";
    x="425"; y="297";
    row = shape+"\t";
    row += (text+"\t");
    row += (x+"\t");
    row += (y+"\t");
    row += (width+"\t");
    row += (height+"\t");
    row += fill;
    data.add(row);

    text="BACE1";//, ASP2, BACE, HSPC104...";
    x="399"; y="230";
    row = shape+"\t";
    row += (text+"\t");
    row += (x+"\t");
    row += (y+"\t");
    row += (width+"\t");
    row += (height+"\t");
    row += fill;
    data.add(row);

    text="ADAM10";//, AD10, AD18, CD156c, CDw156, HsT18717, MADM, RAK, kuz...";
    x="397"; y="127";
    row = shape+"\t";
    row += (text+"\t");
    row += (x+"\t");
    row += (y+"\t");
    row += (width+"\t");
    row += (height+"\t");
    row += fill;
    data.add(row);

    text="TNF";//, DIF, TNF-alpha, TNFA, TNFSF2, TNLG1F";
    x="195"; y="795";
    row = shape+"\t";
    row += (text+"\t");
    row += (x+"\t");
    row += (y+"\t");
    row += (width+"\t");
    row += (height+"\t");
    row += fill;
    data.add(row);

    text="APP";//, AAA, ABETA, ABPP, AD1, APPI, CTFgamma, CVAP, PN-II, PN2, preA4";
    x="276"; y="175";
    row = shape+"\t";
    row += (text+"\t");
    row += (x+"\t");
    row += (y+"\t");
    row += (width+"\t");
    row += (height+"\t");
    row += fill;
    data.add(row);

    // <entry id="31" text="path:hsa05010" type="map"
    //     link="https://www.kegg.jp/dbget-bin/www_bget?hsa05010">
    //     <graphics text="TITLE:Alzheimer disease" fgcolor="#000000" bgcolor="#FFFFFF"
    //          type="roundrectangle" x="132" y="58" width="184" height="25"/>
    // </entry>
    // text="CASP9, APAF-3, APAF3, ICE-LAP6, MCH6, PPP1R56" fgcolor="#000000" bgcolor="#BFFFBF"
    //          type="rectangle" x="810" y="429" width="46" height="17"/>
    // text="CASP12, CASP-12, CASP12P1" fgcolor="#000000" bgcolor="#BFFFBF"
    //          type="rectangle" x="900" y="599" width="46" height="17"/>
    // text="CASP3, CPP32, CPP32B, SCA-1" fgcolor="#000000" bgcolor="#BFFFBF"
    //          type="rectangle" x="885" y="429" width="46" height="17"/>
    // text="CYCS, CYC, HCS, THC4" fgcolor="#000000" bgcolor="#BFFFBF"
    //          type="rectangle" x="712" y="410" width="46" height="17"/>
    // text="APAF1, APAF-1, CED4" fgcolor="#000000" bgcolor="#BFFFBF"
    //          type="rectangle" x="712" y="448" width="46" height="17"/>
    // text="NDUFC2-KCTD14..." fgcolor="#000000" bgcolor="#BFFFBF"
    //          type="rectangle" x="569" y="210" width="46" height="17"/>
    // text="SDHA, CMD1GG, FP, PGL5, SDH1, SDH2, SDHF..." fgcolor="#000000" bgcolor="#BFFFBF"
    //          type="rectangle" x="569" y="239" width="46" height="17"/>
    // text="UQCR11, 0710008D09Rik, QCR10, UQCR..." fgcolor="#000000" bgcolor="#BFFFBF"
    //          type="rectangle" x="569" y="267" width="46" height="17"/>
    // </entry>
    // text="ATP5PD, APT5H, ATP5H, ATPQ..." fgcolor="#000000" bgcolor="#BFFFBF"
    //          type="rectangle" x="569" y="325" width="46" height="17"/>
    // text="COX6B2, COXVIB2, CT59..." fgcolor="#000000" bgcolor="#BFFFBF"
    //          type="rectangle" x="569" y="297" width="46" height="17"/>
    // text="RYR3, RYR-3" fgcolor="#000000" bgcolor="#BFFFBF"
    //          type="rectangle" x="587" y="585" width="46" height="17"/>
    // text="ITPR1, ACV, CLA4, INSP3R1, IP3R, IP3R1, PPP1R94, SCA15, SCA16, SCA29..." fgcolor="#000000" bgcolor="#BFFFBF"
    //          type="rectangle" x="587" y="615" width="46" height="17"/>
    // text="ATP2A1, ATP2A, SERCA1..." fgcolor="#000000" bgcolor="#BFFFBF"
    //          type="rectangle" x="743" y="556" width="46" height="17"/>
    // text="PSEN1, ACNINV3, AD3, FAD, PS-1, PS1, S182..." fgcolor="#000000" bgcolor="#BFFFBF"
    //          type="rectangle" x="679" y="557" width="46" height="17"/>
    // text="GNAQ, CMC1, G-ALPHA-q, GAQ, SWS" fgcolor="#000000" bgcolor="#BFFFBF"
    //          type="rectangle" x="352" y="498" width="46" height="17"/>
    // text="PLCB1, EIEE12, PI-PLC, PLC-154, PLC-I, PLC-beta-1, PLC154, PLCB1A, PLCB1B..." fgcolor="#000000" bgcolor="#BFFFBF"
    //          type="rectangle" x="424" y="499" width="46" height="17"/>
    // text="C01245" fgcolor="#000000" bgcolor="#FFFFFF"
    //          type="circle" x="425" y="540" width="8" height="8"/>
    // text="GRIN1, GluN1, MRD8, NDHMSD, NDHMSR, NMD-R1, NMDA1, NMDAR1, NR1..." fgcolor="#000000" bgcolor="#BFFFBF"
    //          type="rectangle" x="278" y="597" width="46" height="17"/>
    // text="CACNA1C, CACH2, CACN2, CACNL1A1, CCHL1A1, CaV1.2, LQT8, TS, TS._LQT8..." fgcolor="#000000" bgcolor="#BFFFBF"
    //          type="rectangle" x="278" y="632" width="46" height="17"/>
    // text="C00076" fgcolor="#000000" bgcolor="#FFFFFF"
    //          type="circle" x="408" y="595" width="8" height="8"/>
    // text="HSD17B10, 17b-HSD10, ABAD, CAMR, DUPXp11.22, ERAB, HADH2, HCD2, HSD10MD, MHBD, MRPP2, MRX17, MRX31, MRXS10, SCHAD, SDR5C1" fgcolor="#000000" bgcolor="#BFFFBF"
    //          type="rectangle" x="637" y="334" width="46" height="17"/>
    // text="C00076" fgcolor="#000000" bgcolor="#FFFFFF"
    //          type="circle" x="744" y="514" width="8" height="8"/>
    // text="CAPN1, CANP, CANP1, CANPL1, SPG76, muCANP, muCL..." fgcolor="#000000" bgcolor="#BFFFBF"
    //          type="rectangle" x="409" y="701" width="46" height="17"/>
    // text="CDK5R1, CDK5P35, CDK5R, NCK5A, p23, p25, p35, p35nck5a" fgcolor="#000000" bgcolor="#BFFFBF"
    //          type="rectangle" x="409" y="752" width="46" height="17"/>
    // text="CDK5R1, CDK5P35, CDK5R, NCK5A, p23, p25, p35, p35nck5a" fgcolor="#000000" bgcolor="#BFFFBF"
    //          type="rectangle" x="498" y="752" width="46" height="17"/>
    // text="MAPT, DDPAC, FTDP-17, MAPTL, MSTD, MTBT1, MTBT2, PPND, PPP1R103, TAU" fgcolor="#000000" bgcolor="#BFFFBF"
    //          type="rectangle" x="611" y="772" width="46" height="17"/>
    // </entry>
    // <entry id="85" text="hsa:355 hsa:7132" type="gene"
    //     link="https://www.kegg.jp/dbget-bin/www_bget?hsa:355+hsa:7132">
    //     <graphics text="FAS, ALPS1A, APO-1, APT1, CD95, FAS1, FASTM, TNFRSF6..." fgcolor="#000000" bgcolor="#BFFFBF"
    //          type="rectangle" x="277" y="432" width="46" height="17"/>
    // </entry>
    // <entry id="86" text="hsa:8772" type="gene"
    //     link="https://www.kegg.jp/dbget-bin/www_bget?hsa:8772">
    //     <graphics text="FADD, GIG3, MORT1" fgcolor="#000000" bgcolor="#BFFFBF"
    //          type="rectangle" x="350" y="433" width="46" height="17"/>
    // </entry>
    // <entry id="87" text="hsa:841" type="gene"
    //     link="https://www.kegg.jp/dbget-bin/www_bget?hsa:841">
    //     <graphics text="CASP8, ALPS2B, CAP4, Casp-8, FLICE, MACH, MCH5" fgcolor="#000000" bgcolor="#BFFFBF"
    //          type="rectangle" x="423" y="433" width="46" height="17"/>
    // </entry>
    // <entry id="88" text="hsa:637" type="gene"
    //     link="https://www.kegg.jp/dbget-bin/www_bget?hsa:637">
    //     <graphics text="BID, FP497" fgcolor="#000000" bgcolor="#BFFFBF"
    //          type="rectangle" x="494" y="433" width="46" height="17"/>
    // </entry>
    // <entry id="96" text="hsa:5594 hsa:5595" type="gene"
    //     link="https://www.kegg.jp/dbget-bin/www_bget?hsa:5594+hsa:5595">
    //     <graphics text="MAPK1, ERK, ERK-2, ERK2, ERT1, MAPK2, P42MAPK, PRKM1, PRKM2, p38, p40, p41, p41mapk, p42-MAPK..." fgcolor="#000000" bgcolor="#BFFFBF"
    //          type="rectangle" x="589" y="502" width="46" height="17"/>
    // </entry>
    // <entry id="101" text="path:hsa00190" type="map"
    //     link="https://www.kegg.jp/dbget-bin/www_bget?hsa00190">
    //     <graphics text="Oxidative phosphorylation" fgcolor="#000000" bgcolor="#FFFFFF"
    //          type="roundrectangle" x="569" y="137" width="113" height="34"/>
    // </entry>
    // <entry id="102" text="path:hsa04210" type="map"
    //     link="https://www.kegg.jp/dbget-bin/www_bget?hsa04210">
    //     <graphics text="Apoptosis" fgcolor="#000000" bgcolor="#FFFFFF"
    //          type="roundrectangle" x="887" y="400" width="113" height="25"/>
    // </entry>
    // <entry id="103" text="path:hsa04020" type="map"
    //     link="https://www.kegg.jp/dbget-bin/www_bget?hsa04020">
    //     <graphics text="Calcium signaling pathway" fgcolor="#000000" bgcolor="#FFFFFF"
    //          type="roundrectangle" x="524" y="650" width="113" height="34"/>
    // </entry>
    // <entry id="107" text="hsa:4842" type="gene"
    //     link="https://www.kegg.jp/dbget-bin/www_bget?hsa:4842">
    //     <graphics text="NOS1, IHPS1, N-NOS, NC-NOS, NOS, bNOS, nNOS" fgcolor="#000000" bgcolor="#BFFFBF"
    //          type="rectangle" x="468" y="701" width="46" height="17"/>
    // </entry>
    // <entry id="109" text="cpd:C00533" type="compound"
    //     link="https://www.kegg.jp/dbget-bin/www_bget?C00533">
    //     <graphics text="C00533" fgcolor="#000000" bgcolor="#FFFFFF"
    //          type="circle" x="561" y="702" width="8" height="8"/>
    // </entry>
    // <entry id="111" text="cpd:C16845" type="compound"
    //     link="https://www.kegg.jp/dbget-bin/www_bget?C16845">
    //     <graphics text="C16845" fgcolor="#000000" bgcolor="#FFFFFF"
    //          type="circle" x="638" y="703" width="8" height="8"/>
    // </entry>
    // <entry id="118" text="hsa:9451" type="gene"
    //     link="https://www.kegg.jp/dbget-bin/www_bget?hsa:9451">
    //     <graphics text="EIF2AK3, PEK, PERK, WRS" fgcolor="#000000" bgcolor="#BFFFBF"
    //          type="rectangle" x="659" y="640" width="46" height="17"/>
    // </entry>
    // <entry id="119" text="hsa:2081" type="gene"
    //     link="https://www.kegg.jp/dbget-bin/www_bget?hsa:2081">
    //     <graphics text="ERN1, IRE1, IRE1P, IRE1a, hIRE1p" fgcolor="#000000" bgcolor="#BFFFBF"
    //          type="rectangle" x="714" y="640" width="46" height="17"/>
    // </entry>
    // <entry id="120" text="hsa:22926" type="gene"
    //     link="https://www.kegg.jp/dbget-bin/www_bget?hsa:22926">
    //     <graphics text="ATF6, ACHM7, ATF6A" fgcolor="#000000" bgcolor="#BFFFBF"
    //          type="rectangle" x="768" y="640" width="46" height="17"/>
    // </entry>
    // <entry id="129" text="hsa:348" type="gene"
    //     link="https://www.kegg.jp/dbget-bin/www_bget?hsa:348">
    //     <graphics text="APOE, AD2, APO-E, ApoE4, LDLCQ5, LPG" fgcolor="#000000" bgcolor="#BFFFBF"
    //          type="rectangle" x="211" y="401" width="46" height="17"/>
    // </entry>
    // <entry id="133" text="hsa:163688 hsa:51806 hsa:801 hsa:805 hsa:808 hsa:810 hsa:91860" type="gene"
    //     link="https://www.kegg.jp/dbget-bin/www_bget?hsa:163688+hsa:51806+hsa:801+hsa:805+hsa:808+hsa:810+hsa:91860">
    //     <graphics text="CALML6, CAGLP..." fgcolor="#000000" bgcolor="#BFFFBF"
    //          type="rectangle" x="567" y="455" width="46" height="17"/>
    // </entry>
    // <entry id="134" text="hsa:5530 hsa:5532 hsa:5533 hsa:5534 hsa:5535" type="gene"
    //     link="https://www.kegg.jp/dbget-bin/www_bget?hsa:5530+hsa:5532+hsa:5533+hsa:5534+hsa:5535">
    //     <graphics text="PPP3CA, ACCIID, CALN, CALNA, CALNA1, CCN1, CNA1, IECEE, IECEE1, PPP2B..." fgcolor="#000000" bgcolor="#BFFFBF"
    //          type="rectangle" x="637" y="455" width="46" height="17"/>
    // </entry>
    // <entry id="135" text="hsa:572" type="gene"
    //     link="https://www.kegg.jp/dbget-bin/www_bget?hsa:572">
    //     <graphics text="BAD, BBC2, BCL2L8" fgcolor="#000000" bgcolor="#BFFFBF"
    //          type="rectangle" x="655" y="415" width="46" height="17"/>
    // </entry>
    // <entry id="139" text="hsa:3416" type="gene"
    //     link="https://www.kegg.jp/dbget-bin/www_bget?hsa:3416">
    //     <graphics text="IDE, INSULYSIN" fgcolor="#000000" bgcolor="#BFFFBF"
    //          type="rectangle" x="127" y="324" width="46" height="17"/>
    // </entry>
    // <entry id="140" text="hsa:4311" type="gene"
    //     link="https://www.kegg.jp/dbget-bin/www_bget?hsa:4311">
    //     <graphics text="MME, CALLA, CD10, CMT2T, NEP, SCA43, SFE" fgcolor="#000000" bgcolor="#BFFFBF"
    //          type="rectangle" x="127" y="360" width="46" height="17"/>
    // </entry>
    // <entry id="143" text="hsa:322" type="gene"
    //     link="https://www.kegg.jp/dbget-bin/www_bget?hsa:322">
    //     <graphics text="APBB1, FE65, MGC:9072, RIR" fgcolor="#000000" bgcolor="#BFFFBF"
    //          type="rectangle" x="356" y="177" width="46" height="17"/>
    // text="LRP1, A2MR, APOER, APR, CD91, IGFBP-3R, IGFBP3R, IGFBP3R1, KPA, LRP, LRP1A, TGFBR5" fgcolor="#000000" bgcolor="#BFFFBF"
    //          type="rectangle" x="277" y="392" width="46" height="17"/>
    // text="LPL, HDLCQ11, LIPD" fgcolor="#000000" bgcolor="#BFFFBF"
    //          type="rectangle" x="211" y="384" width="46" height="17"/>
    // text="GAPDH, G3PD, GAPD, HEL-S-162eP" fgcolor="#000000" bgcolor="#BFFFBF"
    //          type="rectangle" x="356" y="201" width="46" height="17"/>
    // text="NAE1, A-116A10.1, APPBP1, HPP1, ula-1" fgcolor="#000000" bgcolor="#BFFFBF"
    //          type="rectangle" x="356" y="153" width="46" height="17"/>
    // text="CASP3, CPP32, CPP32B, SCA-1" fgcolor="#000000" bgcolor="#BFFFBF"
    //          type="rectangle" x="663" y="814" width="46" height="17"/>
    // text="CASP7, CASP-7, CMH-1, ICE-LAP3, LICE2, MCH3" fgcolor="#000000" bgcolor="#BFFFBF"
    //          type="rectangle" x="663" y="837" width="46" height="17"/>
    // text="GSK3B" fgcolor="#000000" bgcolor="#BFFFBF"
    //          type="rectangle" x="580" y="806" width="46" height="17"/>
    // text="SNCA, NACP, PARK1, PARK4, PD1" fgcolor="#000000" bgcolor="#BFFFBF"
    //          type="rectangle" x="127" y="503" width="46" height="17"/>
    // text="IL1B, IL-1, IL1-BETA, IL1F2" fgcolor="#000000" bgcolor="#BFFFBF"
    //          type="rectangle" x="195" y="831" width="46" height="17"/>
    // text="C00076" fgcolor="#000000" bgcolor="#FFFFFF"
    //          type="circle" x="681" y="513" width="8" height="8"/>
    // text="C00027" fgcolor="#000000" bgcolor="#FFFFFF"
    //          type="circle" x="238" y="751" width="8" height="8"/>
    // text="C00070" fgcolor="#000000" bgcolor="#FFFFFF"
    //          type="circle" x="201" y="695" width="8" height="8"/>
    // text="C14818" fgcolor="#000000" bgcolor="#FFFFFF"
    //          type="circle" x="201" y="725" width="8" height="8"/>
    // text="RTN3, ASYIP, HAP, NSPL2, NSPLII, RTN3-A1..." fgcolor="#000000" bgcolor="#BFFFBF"
    //          type="rectangle" x="463" y="252" width="46" height="17"/>

//     <entry id="187" text="undefined" type="group">
//         <graphics fgcolor="#000000" bgcolor="#FFFFFF"
//              type="rectangle" x="211" y="392" width="46" height="34"/>
//         <component id="129"/>
//         <component id="148"/>
//     </entry>


//     <relation entry1="26" (  x="276"; y="175";) entry2="157" ( x="356" y="153") type="PPrel">
//         <subtype text="binding/association" value="---"/>
//     </relation>
//     <relation entry1="26" entry2="143" type="PPrel">
//         <subtype text="binding/association" value="---"/>
//     </relation>


ArrayList<String> connections = new ArrayList<String>();
header = "type\t"+
  "x1\t"+
  "y1\t"+
  "x2\t"+
  "y2";
connections.add(header);

String type = "binding/association";
String x1 = "276";
String y1 = "175";
String x2 = "356";
String y2 = "153";

row = type+"\t";
row += (x1+"\t");
row += (y1+"\t");
row += (x2+"\t");
row += y2;
connections.add(row);
//     <relation entry1="187" entry2="147" type="PPrel">
//         <subtype text="activation" value="--&gt;"/>
//     </relation>
//     <relation entry1="85" entry2="86" type="PPrel">
//         <subtype text="activation" value="--&gt;"/>
//     </relation>
//     <relation entry1="86" entry2="87" type="PPrel">
//         <subtype text="activation" value="--&gt;"/>
//     </relation>
//     <relation entry1="87" entry2="88" type="PPrel">
//         <subtype text="activation" value="--&gt;"/>
//     </relation>
//     <relation entry1="50" entry2="51" type="PPrel">
//         <subtype text="activation" value="--&gt;"/>
//     </relation>
//     <relation entry1="51" entry2="52" type="PCrel">
//         <subtype text="activation" value="--&gt;"/>
//     </relation>
//     <relation entry1="133" entry2="134" type="PPrel">
//         <subtype text="activation" value="--&gt;"/>
//     </relation>
//     <relation entry1="134" entry2="135" type="PPrel">
//         <subtype text="activation" value="--&gt;"/>
//         <subtype text="dephosphorylation" value="-p"/>
//     </relation>
//     <relation entry1="35" entry2="32" type="PPrel">
//         <subtype text="activation" value="--&gt;"/>
//     </relation>
//     <relation entry1="36" entry2="32" type="PPrel">
//         <subtype text="activation" value="--&gt;"/>
//     </relation>
//     <relation entry1="32" entry2="34" type="PPrel">
//         <subtype text="activation" value="--&gt;"/>
//     </relation>
//     <relation entry1="48" entry2="118" type="PPrel">
//         <subtype text="inhibition" value="--|"/>
//     </relation>
//     <relation entry1="48" entry2="119" type="PPrel">
//         <subtype text="inhibition" value="--|"/>
//     </relation>
//     <relation entry1="48" entry2="120" type="PPrel">
//         <subtype text="inhibition" value="--|"/>
//     </relation>
//     <relation entry1="107" entry2="109" type="PCrel">
//         <subtype text="activation" value="--&gt;"/>
//     </relation>
//     <relation entry1="59" entry2="67" type="PCrel">
//         <subtype text="activation" value="--&gt;"/>
//     </relation>
//     <relation entry1="67" entry2="68" type="PPrel">
//         <subtype text="activation" value="--&gt;"/>
//     </relation>
//     <relation entry1="68" entry2="69" type="PPrel">
//         <subtype text="state change" value="..."/>
//     </relation>
//     <relation entry1="69" entry2="71" type="PPrel">
//         <subtype text="phosphorylation" value="+p"/>
//     </relation>
//     <relation entry1="70" entry2="71" type="PPrel">
//         <subtype text="phosphorylation" value="+p"/>
//     </relation>
//     <relation entry1="163" entry2="71" type="PPrel">
//         <subtype text="phosphorylation" value="+p"/>
//     </relation>
//     <relation entry1="26" entry2="154" type="PPrel">
//         <subtype text="inhibition" value="--|"/>
//     </relation>
//     <relation entry1="52" entry2="46" type="PCrel">
//         <subtype text="activation" value="--&gt;"/>
//     </relation>
// </pathway>

    // The data retrieved from the database
    //Pathway pathway = (Pathway) reportObject.getObject();
    //Pathway pathway = new Pathway()
    // InterMineObject gene = (InterMineObject) reportObject.getObject();



    // try{
      // A pathway has a collection of genes associated, we iterate over them
      // to retrieve the information needed for their display
      // Set<ProbeSet> probeSets = (Set<ProbeSet>) pathway.getFieldValue("genes");
    //   for( ProbeSet ps: probeSets ){hsa05010
    //
    //     // Each probeSet has a collection of Expression objects associated, we
    //     // process each individually
    //     Set<Expression> expressions = (Set<Expression>) ps.getFieldValue("expressions");
    //     for( Expression exp: expressions ){
    //
    //       String probeID = (String)ps.getFieldValue("probeSetId");
    //       // For each expression value, we need to store the following information
    //       // tissue (hbiTissue)
    //       // |-- category (String)
    //       // |-- organ (String)
    //       // |-- name (String)
    //       // call (String <enum>['P', 'A', 'M'])
    //       // value (float)
    //       Tissue tissue = (HbiTissue) exp.getFieldValue("tissue");
    //       String category = (String) tissue.getFieldValue("category");
    //       String organ = (String) tissue.getFieldValue("organ");
    //       String name = (String) tissue.getFieldValue("name");
    //
    //       String call = (String) exp.getFieldValue("call");
    //       float value = (Float) exp.getFieldValue("value");
    //
    //       row = probeID+"\t";
    //       row += (category+"\t");
    //       row += (organ+"\t");
    //       row += (name+"\t");
    //       row += (call+"\t");
    //       row += value;
    //
    //       data.add(row);
    //     }
    //
    // }
      /* fill the resulting table with the data */
      // Use the identifier of the pathway as a name when initializing the structure
      // request.setAttribute("pathway", (String) pathway.getFieldValue("identifier"));
      request.setAttribute("pathway", "hsa05010");
      // pass all graphical data
      request.setAttribute("data", data);
      request.setAttribute("connections", connections);

    // } //try
    // catch(IllegalAccessException e){
    //   logger.error(e.getMessage());
    // }
  }
}
